import React from 'react';
import {PolicySection} from '../../../../../common/components';

const TOSDisclaimer = () => {
  return (
    <PolicySection
      title="Disclaimers and Limitation of Liability"
      content={`YOUR USE OF THE Eggnation and Applicnation FAMILY OF APPLICATIONS AND SITES IS ON AN "AS IS," "AS AVAILABLE" BASIS, AND WE SPECIFICALLY DISCLAIM ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT WARRANT THAT THE PLATFORM OR SERVICE WILL BE UNINTERRUPTED OR ERROR FREE OR FREE FROM VIRUSES OR OTHER HARMFUL MALICIOUS AGENTS. TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIGENCE), CONTRACT OR OTHERWISE, SHALL Eggnation and Applicnation, ITS AFFILIATES, AND ITS AND THEIR RESPECTIVE SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, ADVERTISERS, SUPPLIERS, CONTENT PROVIDERS AND LICENSORS (COLLECTIVELY, THE “Eggnation and Applicnation PARTIES”) BE LIABLE (JOINTLY OR SEVERALLY) TO YOU OR ANY OTHER PERSON AS A RESULT OF YOUR USE OF THE Eggnation and Applicnation FAMILY OF APPLICATIONS AND SITES FOR INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, EXEMPLARY OR PUNITIVE DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. WHERE WE ARE NOT LEGALLY ENTITLED TO EXCLUDE ALL LIABILITY, OUR TOTAL LIABILITY FOR ANY LOSS OR DAMAGE RELATING TO THE Eggnation and Applicnation FAMILY OF APPLICATIONS AND SITES SHALL NOT EXCEED AN AMOUNT EQUAL TO THE SUBSCRIPTION FEES (IF ANY) PAID BY YOU TO US. `}
    />
  );
};

export default TOSDisclaimer;
